### PR TITLE
Cleanup and move to Firmware install scripts

### PR DESCRIPTION
**Pull request by julianoes**
WIP. For more info see commits.

### CODE REVIEW

**Comment by julianoes** [comment]
@dagar what's your hunch regarding base image with everything included versus many variants extending it as we have it now. So for instance, do you think it makes sense to have a separate image for clang, raspi, etc.?

**Comment by dagar** [comment]
> @dagar what's your hunch regarding a base image with everything included versus many variants extending it as we have it now. So for instance, do you think it makes sense to have a separate image for clang, raspi, etc.?

I think the only real benefit is trying to keep the size under control given that every single CI build is pulling these many times.

You should be able to see the numbers on docker hub.

Screen Shot 2020-12-01 at 5 27 05 PM

Merging base + nuttx could be fine and worth the effort if we strip it down the minimum (I started this earlier).

I suspect we don't really need separate images for simulation and ros.

**Comment by dagar** [comment]
I also don't particularly want to maintain these for multiple versions of Ubuntu other than maybe a transition period.

We could stop doing that for everything except ROS.

**Comment by julianoes** [comment]
I would argue that it makes sense to generate the containers for 18.04 and 20.04 if that's what we support. If we decided to only support 20.04, then sure, we can remove 18.04.

For the clang or armhf case, we could also just install the additional stuff on each CI run, right?

Regarding size of the images, one thing to fix is to clean up the apt-get caches after running ubuntu.sh. That's currently missing.

**Comment by dagar** [comment]
> I would argue that it makes sense to generate the containers for 18.04 and 20.04 if that's what we support. If we decided to only support 20.04, then sure, we can remove 18.04.

I suppose it depends what we're actually trying to accomplish here. The idea of having a container for everything we wanted to claim to support kind of fell apart with docker hub taking the better part of a day to build everything and update (*if* you didn't make a mistake) and lack of CI resources. Even for 18.04 + 20.04 we ended up dropping most of the 18.04 builds as soon as 20.04 was verified because we couldn't afford both, so it's not really getting much testing beyond the setup.

If there's interest in both getting the container sprawl under control and actually getting basic testing in place to support a wide range of distros + releases I think I'd want to propose taking a step back and simplifying quite a bit. Refocusing on the original idea of providing "sanctioned" PX4 development environments for a couple core use cases.
 1. px4-dev
     - merged px4-dev-base + px4-dev-nuttx + px4-dev-armhf (maybe), but carefully stripped down to keep the size reasonable
     - whichever distro we think is currently "best" for typical PX4 dev right now (likely Ubuntu 20.04 today, but could be Fedora tomorrow, etc)
 2. px4-dev-rosX
      - limited to a much smaller set of ROS/ROS2 versions that we're actually going to test
      - likely doesn't depend on px4-dev, the tagging and docker hub juggling probably isn't worth the effort
 3. Separately have low frequency builds (eg nightly or on Tools/setup changes) intended to maintain basic support across every distro version we claim to support
    - start with clean official distro container, run setup.sh, make quick_check
        - repeat for Ubuntu:18.04-20.10, Fedora:X, Arch, etc, etc


> For the clang or armhf case, we could also just install the additional stuff on each CI run, right?

That tends to be brittle over time as available package versions change (or are limited) in ways you can't control. Anything we'd actually want people to fly is best to keep versioned so that you can always jump back to a specific version of PX4 and build using the exact same environment that was supported at the time. For random side builds like clang (clang-tidy, etc) installing on CI is probably fine.

**Comment by julianoes** [comment]
Not required anymore, thanks to @mrpollo for continuing in https://github.com/PX4/PX4-Autopilot/pull/18869.

**Pull request closed without merging**
